# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{progress}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Boba Fat"]
  s.date = %q{2010-12-09}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Manifest",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/progress.rb",
    "lib/progress/active_record.rb",
    "lib/progress/enumerable.rb",
    "lib/progress/integer.rb",
    "lib/progress/kernel.rb",
    "lib/progress/with_progress.rb",
    "progress.gemspec",
    "spec/progress_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/toy/progress}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Show progress of long running tasks}
  s.test_files = [
    "spec/progress_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rake-gem-ghost>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

